name: Search-dockerHub-Images

on:
  workflow_dispatch:
    inputs:
      page_size:
        description: '请填写page_size'
        required: true
        default: '50' 
      arch:
        description: '请填写docker镜像的arch: amd64或者arm64'
        required: true
        default: 'arm64'    
      docker_images:
        description: '请填写搜索的关键词,多个用英文逗号分开'
        required: true
        default: 'alpine,nginx,busybox,llama.cpp'

jobs:
  search_and_package:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Search DockerHub Images tags
        run: |
          df -h
          pwd && ls
          images="${{ github.event.inputs.docker_images }}"
          arch="${{ inputs.arch}}"
          pagesize="${{ inputs.page_size }}"
          IFS=',' read -r -a image_array <<< "$images"
          success=false
          for image in "${image_array[@]}"; do
            if curl -f -o "${image}.search.txt" "https://hub.docker.com/search.data?q=${image}&type=image&architecture=${arch}&operating_system=linux&page_size=${pagesize}&_routes=routes%2F_layout.search"; then
              echo "Downloaded tags for $image"
              success=true
              python parse_dockerhub_json.py "${image}.search.txt"
              curl -f -o "${image}.pull_count.search.txt" "https://hub.docker.com/search.data?q=${image}&type=image&architecture=${arch}&operating_system=linux&page_size=${pagesize}&sort=pull_count&order=desc&_routes=routes%2F_layout.search"
              curl -f -o "${image}.update.search.txt" "https://hub.docker.com/search.data?q=${image}&type=image&architecture=${arch}&operating_system=linux&page_size=${pagesize}&sort=updated_at&order=desc&_routes=routes%2F_layout.search"
             
            else
              echo "Failed to fetch tags for $image" >&2
            fi
          done
          if ! $success; then
            echo "No Search files were downloaded. Exiting." >&2
            exit 2
          fi
          ls -l
          if [ -f "${image}.update.search.txt" ]; then
            python parse_dockerhub_json.py "${image}.update.search.txt"
          fi
          tar -czvf "${image}.search.gz" *.txt *.csv *.json
          rm *.txt
          # for image in "${image_array[@]}"; do
          #   curl -o "${image}.tags.txt" https://registry.hub.docker.com/v2/repositories/${namespace}/${image}/tags?page=1&page_size=50 
          # done
          # ls -l
          # tar -czvf images.search.gz *.txt

      - name: List generated files (debug step)
        run: |
          echo "Preparing release (.gz) files:"
          find $GITHUB_WORKSPACE -name "*.gz"
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: DockerTarBuilder-ARM64
          name: ${{ env.RELEASE_NAME }} for arm64
          body: |
            [![Github](https://img.shields.io/badge/RELEASE:DockerTarBuilder-123456?logo=github&logoColor=fff&labelColor=green&style=for-the-badge)](https://www.bilibili.com/video/BV1EZ421M7mL) [![Github](https://img.shields.io/badge/国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://wkdaily.cpolar.top/archives/1)
            ### How to use? For example
            `docker load -i alpine_latest.tar.gz `
            ### Video teaching
            [![Bilibili](https://img.shields.io/badge/Bilibili-123456?logo=bilibili&logoColor=fff&labelColor=fb7299)](https://www.bilibili.com/video/BV1yyq6YREdF)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload DockerHub images.search.gz as release assets
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: DockerTarBuilder-ARM64
          files: ${{ github.workspace }}/*.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
