name: download_files

on:
  workflow_dispatch:
    inputs:
      url:
        description: '请填写下载地址URL,空格用%20'
        required: true
        default: 'https://huggingface.co/api/models?search=qwen'
      target_filename:
        description: '请填写保存的文件名,不指定名称输入null'
        required: true
        default: 'result.txt'
      options:
        description: 'curl 参数，例如：-X POST'
        required: false
        default: ''        
      data_options:
        description: 'curl 数据参数，例如：-d "download=1" '
        required: false
        default: ''         

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: download_file
        run: |
          mkdir .download || rm -r .download/
          cd .download
          url="${{ inputs.url }}"
          filename="${{ inputs.target_filename }}"
          options="${{ inputs.options }}"
          opt="-o ${filename}"
          dataOpts="${{ inputs.data_options }}"
          if [ "$filename" = "null" ]; then opt="-O" ; fi
          echo "curl -L ${options} ${opt}   ${url}  ${dataOpts}"
          curl -L ${options} ${opt}  "${url}"  ${dataOpts}
          ls -l
          cd ..
          

      - name: List generated files (debug step)
        run: |
          find $GITHUB_WORKSPACE -name "*.txt"
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: DockerTarBuilder-AMD64
          name: ${{ env.RELEASE_NAME }} for x86-64
          body: |
            [![Github](https://img.shields.io/badge/RELEASE:DockerTarBuilder-123456?logo=github&logoColor=fff&labelColor=green&style=for-the-badge)](https://www.bilibili.com/video/BV1EZ421M7mL) [![Github](https://img.shields.io/badge/国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://wkdaily.cpolar.top/archives/1)
            ### How to use? For example
            `docker load -i alpine_latest.tar.gz `
            ### Video teaching
            [![Bilibili](https://img.shields.io/badge/Bilibili-123456?logo=bilibili&logoColor=fff&labelColor=fb7299)](https://www.bilibili.com/video/BV1yyq6YREdF)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload download file as release assets
        uses: softprops/action-gh-release@v2.3.3
        with:
          tag_name: DockerTarBuilder-AMD64
          files: ${{ github.workspace }}/.download/*
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
