name: Save WebPage by wget

on: 
  workflow_dispatch:
    inputs:
      url:
        description: '网页的url'
        required: true
        default: 'https://github.com'
      option:
        description: 'wget的option，例如：-np'
        required: true
        default: ''        

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependency
        run: |
          id
          # sudo apt update && sudo apt install -y chromium
          # sudo snap install chromium
  
      - name: Create HTML from Webpage
        run: |
          id
          option=${{ inputs.option }}
          wget --help
          # 测试网页包含iframe: https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard
          # 测试网页包含表格需要滑动翻页：https://open-llm-leaderboard-open-llm-leaderboard.hf.space/#/
          mkdir output
          cd output
          wget -mkEpnH --user-agent="Mozilla/5.0"  $option --wait=1 --random-wait  "$WEBPAGE_URL"  || echo 0
        env:
          # 在这里设置你的 URL 环境变量
          WEBPAGE_URL: ${{ inputs.url }} 
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpage-html
          path: ${{ github.workspace }}/output
          retention-days: 2  # 将保留天数设置为 1 天 最多可设置90天
