name: Save WebPage by monolith

on: 
  workflow_dispatch:
    inputs:
      url:
        description: '网页的url'
        required: true
        default: 'https://github.com'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install monolith
        run: |
          id
          sudo apt update && sudo apt install -y chromium
          sudo snap install monolith
  
      - name: Create HTML from Webpage
        run: |
          id
          monolith --help
          chromium --headless --window-size=1920,1080 --run-all-compositor-stages-before-draw --virtual-time-budget=9000 --incognito --dump-dom "$WEBPAGE_URL" | monolith - -I -b "$WEBPAGE_URL" -o webpage.html
          # monolith "$WEBPAGE_URL"  -o webpage.html
        env:
          # 在这里设置你的 URL 环境变量
          WEBPAGE_URL: ${{ inputs.url }} 
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpage-html
          path: ${{ github.workspace }}/*.html
          retention-days: 2  # 将保留天数设置为 1 天 最多可设置90天
