name: Save WebPage to PDF by Puppeteer

on: 
  workflow_dispatch:
    inputs:
      url:
        description: '网页的url'
        required: true
        default: 'https://github.com'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: npm install puppeteer
  
      - name: Create PDF from Webpage
        run: |
          node puppeteer/save-webpage-pdf.cjs
          ls -l
          ls -l puppeteer
        env:
          # 在这里设置你的 URL 环境变量
          WEBPAGE_URL: ${{ inputs.url }} 
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpage-pdf
          path: ${{ github.workspace }}/*.mhtml
          retention-days: 2  # 将保留天数设置为 1 天 最多可设置90天
