name: Save WebPage by wget

on: 
  workflow_dispatch:
    inputs:
      url:
        description: '网页的url'
        required: true
        default: 'https://github.com'
      level:
        description: 'wget最大递归深度；网页内容多的话一定要限制递归深度'
        required: true
        default: '2'  
        
      option:
        description: 'wget的option， 例如：-np -mkEpnH'
        required: true
        default: ''        

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependency
        run: |
          id
          # sudo apt update && sudo apt install -y chromium
          # sudo snap install chromium
  
      - name: Create HTML from Webpage
        run: |
          id
          option=${{ inputs.option }}
          level=${{ inputs.level }}
          mapfile -t arr <<< "$option"
          wget --help
          # 测试网页包含iframe: https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard
          # 测试网页包含表格需要滑动翻页：https://open-llm-leaderboard-open-llm-leaderboard.hf.space/#/
          mkdir output
          cd output
          wget  "${arr[@]}"  --user-agent="Mozilla/5.0"  -l "$level" --wait=1 --random-wait  "$WEBPAGE_URL"  || echo 0
          ls
        env:
          # 在这里设置你的 URL 环境变量
          WEBPAGE_URL: ${{ inputs.url }} 
    
      - name: Clean up file names
        run: |
          cd output
          # 定义非法字符集
          ILLEGAL_CHARS='"?*:<>|'
          
          # 查找所有包含非法字符的文件
          find . -type f | while read -r file; do
            # 检查文件名是否包含非法字符
            if [[ "$file" =~ [$ILLEGAL_CHARS] ]]; then
              # 替换所有非法字符为下划线
              new_file=$(echo "$file" | tr "[$ILLEGAL_CHARS]" ".")
              # 确保目录存在
              mkdir -p "$(dirname "$new_file")"
              # 重命名文件
              mv "$file" "$new_file"
              echo "Renamed: $file -> $new_file"
            fi
          done          
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpage-html
          path: ${{ github.workspace }}/output
          retention-days: 2  # 将保留天数设置为 1 天 最多可设置90天
