name: Save WebPage to PDF

on: 
  workflow_dispatch:
    inputs:
      url:
        description: '网页的url'
        required: true
        default: 'https://github.com'
      dockerfile_path:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Create PDF from Webpage
        run: |
          # 替换为你想要转换的网页 URL
          url=${{ inputs.url }} 
          wkhtmltopdf "$url" output-wk.pdf    


  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpage-pdf-wk
          path: ${{ github.workspace }}/*.pdf
          retention-days: 2  # 将保留天数设置为 1 天 最多可设置90天
