name: Save WebPage to PDF by Puppeteer

on: 
  workflow_dispatch:
    inputs:
      url:
        description: '网页的url'
        required: true
        default: 'https://github.com'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: npm install puppeteer
  
      - name: Create PDF from Webpage
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
            const page = await browser.newPage();
            await page.setViewport({ width: 1200, height: 800 });
            // 从环境变量中读取 URL
            const url = process.env.WEBPAGE_URL;
            if (!url) {
              console.error('错误：环境变量 WEBPAGE_URL 未设置');
              process.exit(1);
            }
            console.info('url 设置了');
            try {
              // 增加 timeout 时间，例如 60000 毫秒（60秒）
              await page.goto(url, { 
                waitUntil: 'networkidle2', 
                timeout: 60000 
              });
            } catch (error) {
              console.error('页面加载超时或失败:', error);
              await browser.close();
              process.exit(1);
            }
            // await page.goto(url, { waitUntil: 'networkidle2', timeout: 60000 });
            await page.pdf({
              path: 'output.pdf',
              format: 'A4',
              landscape: true,
              printBackground: true
            });
            await browser.close();
          })();
          "
        env:
          # 在这里设置你的 URL 环境变量
          WEBPAGE_URL: ${{ inputs.url }} 
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpage-pdf
          path: ${{ github.workspace }}/*.pdf
          retention-days: 2  # 将保留天数设置为 1 天 最多可设置90天
